from uuid import uuid4

from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()

def deserialize_user(user):
    """Deserializer user instance to JSON."""
    return {
        'id': user.id,
        'username': user.username,
        'email': user.email,
        'first_name': user.first_name,
        'last_name': user.last_name
    }

class TrackableDateModel(models.Model):
    """Abstract model to Track the creation/update date for a model"""

    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

    class Meta:
        abstract = True

    
def _generate_unique_uri():
    """Generates a unique uri for the chat session."""
    return str(uuid4()).replace('-', '')[:15]


class ChatSession(TrackableDateModel):
    """ A Chat Session. The uri's generated by taking the first """

    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    uri = models.URLField(default=_generate_unique_uri)


class ChatSessionMessage(TrackableDateModel):
    """"""